// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// Generated by `npm run gen:reference` from the preset option types. Do not edit.

import type { InteractionPresetType } from '../../core/interaction-spec';

/** One option a preset accepts, as the catalogue describes it. */
export interface InteractionPresetOption {
    readonly name: string;
    /** The option's type, in the notation of the factory types. */
    readonly type: string;
    readonly required: boolean;
    readonly note: string;
}

/** Every option each preset accepts. `id` is omitted: it sits on the spec entry. */
export const INTERACTION_PRESET_OPTIONS: Readonly<Record<InteractionPresetType, readonly InteractionPresetOption[]>> = {
    'click-highlight': [
        { name: "dimOpacity", type: "number", required: false, note: "" },
        { name: "targets", type: "('mark' | 'legend' | 'discreteAxis')[]", required: false, note: "Semantic surfaces activated by this preset. Defaults to all three targets." },
        { name: "reset", type: "ResetGesture[]", required: false, note: "Gestures that return this interaction to its neutral state." },
    ],
    'axis-highlight': [
        { name: "axis", type: "'x' | 'y'", required: false, note: "Limits the preset to one axis; both discrete axes when unset." },
        { name: "event", type: "'hover' | 'click'", required: false, note: "Defaults to 'click'." },
        { name: "dimOpacity", type: "number", required: false, note: "" },
        { name: "reset", type: "ResetGesture[]", required: false, note: "Gestures that return this interaction to its neutral state." },
    ],
    'click-group-focus': [
        { name: "dimOpacity", type: "number", required: false, note: "" },
        { name: "groupBy", type: "string | string[]", required: false, note: "" },
        { name: "reset", type: "ResetGesture[]", required: false, note: "Gestures that return this interaction to its neutral state." },
    ],
    'hover-group-focus': [
        { name: "groupBy", type: "string | string[]", required: true, note: "" },
        { name: "dimOpacity", type: "number", required: false, note: "" },
        { name: "tolerance", type: "number", required: false, note: "Nearest-mark hover radius in renderer pixels. Defaults to 8." },
    ],
    'click-annotate': [
        { name: "dimOpacity", type: "number", required: false, note: "" },
        { name: "reset", type: "ResetGesture[]", required: false, note: "Gestures that return this interaction to its neutral state." },
    ],
    'select': [
        { name: "match", type: "'intersect' | 'contain'", required: false, note: "The marks the region lists: those it touches, or only those it contains. Defaults to 'intersect'." },
        { name: "dimOpacity", type: "number", required: false, note: "" },
        { name: "guide", type: "{ visible?, style?: { fill?, fillOpacity?, stroke?, strokeOpacity?, strokeWidth? } } | false", required: false, note: "Transient region shown during the gesture; false disables visual feedback." },
        { name: "mode", type: "'ephemeral' | 'stateful'", required: false, note: "'stateful' keeps the region on screen and editable after the drag. Defaults to 'ephemeral'." },
        { name: "reset", type: "ResetGesture[]", required: false, note: "Gestures that return this interaction to its neutral state." },
    ],
    'lasso-select': [
        { name: "match", type: "'intersect' | 'contain'", required: false, note: "The marks the region lists: those it touches, or only those it contains. Defaults to 'intersect'." },
        { name: "dimOpacity", type: "number", required: false, note: "" },
        { name: "guide", type: "{ visible?, style?: { fill?, fillOpacity?, stroke?, strokeOpacity?, strokeWidth? } } | false", required: false, note: "Transient region shown during the gesture; false disables visual feedback." },
        { name: "reset", type: "ResetGesture[]", required: false, note: "Gestures that return this interaction to its neutral state." },
    ],
    'brush-x': [
        { name: "match", type: "'intersect' | 'contain'", required: false, note: "The marks the region lists: those it touches, or only those it contains. Defaults to 'intersect'." },
        { name: "dimOpacity", type: "number", required: false, note: "" },
        { name: "guide", type: "{ visible?, style?: { fill?, fillOpacity?, stroke?, strokeOpacity?, strokeWidth? } } | false", required: false, note: "Transient region shown during the gesture; false disables visual feedback." },
        { name: "mode", type: "'ephemeral' | 'stateful'", required: false, note: "'stateful' keeps the region on screen and editable after the drag. Defaults to 'ephemeral'." },
        { name: "reset", type: "ResetGesture[]", required: false, note: "Gestures that return this interaction to its neutral state." },
    ],
    'brush-y': [
        { name: "match", type: "'intersect' | 'contain'", required: false, note: "The marks the region lists: those it touches, or only those it contains. Defaults to 'intersect'." },
        { name: "dimOpacity", type: "number", required: false, note: "" },
        { name: "guide", type: "{ visible?, style?: { fill?, fillOpacity?, stroke?, strokeOpacity?, strokeWidth? } } | false", required: false, note: "Transient region shown during the gesture; false disables visual feedback." },
        { name: "mode", type: "'ephemeral' | 'stateful'", required: false, note: "'stateful' keeps the region on screen and editable after the drag. Defaults to 'ephemeral'." },
        { name: "reset", type: "ResetGesture[]", required: false, note: "Gestures that return this interaction to its neutral state." },
    ],
    'brush-angle': [
        { name: "match", type: "'intersect' | 'contain'", required: false, note: "The marks the region lists: those it touches, or only those it contains. Defaults to 'intersect'." },
        { name: "dimOpacity", type: "number", required: false, note: "" },
        { name: "guide", type: "{ visible?, style?: { fill?, fillOpacity?, stroke?, strokeOpacity?, strokeWidth? } } | false", required: false, note: "Transient region shown during the gesture; false disables visual feedback." },
        { name: "mode", type: "'ephemeral' | 'stateful'", required: false, note: "'stateful' keeps the region on screen and editable after the drag. Defaults to 'ephemeral'." },
        { name: "reset", type: "ResetGesture[]", required: false, note: "Gestures that return this interaction to its neutral state." },
    ],
    'brush-zoom': [
        { name: "axes", type: "'x' | 'y' | 'xy'", required: false, note: "Defaults to 'xy'." },
        { name: "guide", type: "{ visible?, style?: { fill?, fillOpacity?, stroke?, strokeOpacity?, strokeWidth? } } | false", required: false, note: "" },
        { name: "reset", type: "ResetGesture[]", required: false, note: "Returns the viewport to the full frame. Defaults to ['double-click', 'escape']." },
        { name: "transition", type: "{ duration: ms }", required: false, note: "The zoom into the brushed region. Defaults to 400 ms; `{ duration: 0 }` jumps." },
        { name: "resetTransition", type: "{ duration: ms }", required: false, note: "The flight home on reset. Defaults to 400 ms; `{ duration: 0 }` jumps." },
    ],
    'linked-brush': [
        { name: "match", type: "'intersect' | 'contain'", required: false, note: "The marks the region lists: those it touches, or only those it contains. Defaults to 'intersect'." },
        { name: "dimOpacity", type: "number", required: false, note: "" },
        { name: "guide", type: "{ visible?, style?: { fill?, fillOpacity?, stroke?, strokeOpacity?, strokeWidth? } } | false", required: false, note: "Transient region shown during the gesture; false disables visual feedback." },
        { name: "reset", type: "ResetGesture[]", required: false, note: "Gestures that return this interaction to its neutral state." },
        { name: "groupBy", type: "string | string[]", required: true, note: "" },
        { name: "brush", type: "'rectangle' | 'lasso'", required: false, note: "Defaults to 'rectangle'." },
    ],
    'legend-toggle': [
        { name: "mutedOpacity", type: "number", required: false, note: "" },
        { name: "reset", type: "ResetGesture[]", required: false, note: "Hidden series are a setting, so nothing resets them unless this list says so." },
    ],
    'context-activate': [

    ],
    'long-press': [
        { name: "holdMs", type: "number", required: false, note: "Defaults to 500." },
        { name: "dimOpacity", type: "number", required: false, note: "" },
        { name: "reset", type: "ResetGesture[]", required: false, note: "Gestures that return this interaction to its neutral state." },
    ],
    'double-activate': [
        { name: "dimOpacity", type: "number", required: false, note: "" },
        { name: "reset", type: "ResetGesture[]", required: false, note: "Gestures that return this interaction to its neutral state." },
    ],
    'inspect': [
        { name: "mode", type: "'x' | 'y' | 'xy', with an optional comparison such as 'x>' or 'x<=;y>='", required: false, note: "The axes the pointer reads, with an optional comparison per axis. Defaults to 'xy'." },
        { name: "cycle", type: "InspectMode[]", required: false, note: "Ordered modes cycled by wheel or context-menu gestures; mode is included automatically." },
        { name: "tolerance", type: "number", required: false, note: "Hit tolerance as a plot-size fraction. Defaults to 0.02 for XY and 0.01 otherwise." },
        { name: "guide", type: "{ visible?, style?: { color?, opacity?, width?, fillOpacity?, haloColor?, haloOpacity?, haloWidth? } } | false", required: false, note: "Transient guide shown while inspecting; false disables visual feedback." },
        { name: "selector", type: "{ select: { key } }", required: false, note: "" },
        { name: "dimOpacity", type: "number", required: false, note: "" },
    ],
    'inspect-index': [
        { name: "axis", type: "'x' | 'y'", required: false, note: "The axis an index slice is read along. Defaults to the chart's index axis: the temporal one, else the discrete one beside a measure, else x." },
        { name: "tolerance", type: "number", required: false, note: "Near-axis acquisition radius as a plot-size fraction. Defaults to 0.01." },
        { name: "show", type: "'all' | 'single' | { series: value }", required: false, note: "Which series to present: all, the first series, or a preferred initial series." },
        { name: "seriesBy", type: "string", required: false, note: "Record field identifying a series; single-series policies switch through the legend." },
        { name: "displayValue", type: "boolean", required: false, note: "Show compact series-colored labels on value guides inside the plot. Defaults to true." },
        { name: "guide", type: "{ visible?, style?: { color?, opacity?, width?, fillOpacity?, haloColor?, haloOpacity?, haloWidth? } } | false", required: false, note: "" },
        { name: "selector", type: "{ select: { key } }", required: false, note: "" },
        { name: "reset", type: "ResetGesture[]", required: false, note: "Releases a locked series. Defaults to ['escape']." },
    ],
    'navigate': [
        { name: "axes", type: "'x' | 'y' | 'xy' | 'available'", required: false, note: "'available' navigates every axis the chart confirms. Defaults to 'available'." },
        { name: "pan", type: "boolean", required: false, note: "Defaults to true." },
        { name: "zoom", type: "boolean", required: false, note: "Defaults to true." },
        { name: "wheelSensitivity", type: "number", required: false, note: "Defaults to 0.002." },
        { name: "domainGuard", type: "{ minVisibleFraction?, maxVisibleFraction?, overscrollFraction? }", required: false, note: "" },
        { name: "reset", type: "ResetGesture[]", required: false, note: "Returns the viewport to the full frame. Defaults to ['double-click']." },
        { name: "resetTransition", type: "{ duration: ms }", required: false, note: "The flight home on reset. Defaults to 400 ms; `{ duration: 0 }` jumps." },
    ],
    'drag-reorder': [
        { name: "reset", type: "ResetGesture[]", required: false, note: "The order is a setting, so nothing resets it unless this list says so." },
    ],
    'accessible-navigation': [
        { name: "emphasis", type: "boolean", required: false, note: "Dim the marks outside the focused element, as a click highlight does. Defaults to true." },
        { name: "dimOpacity", type: "number", required: false, note: "" },
        { name: "caption", type: "boolean", required: false, note: "Show a visible caption naming the focused element and its content. Defaults to true." },
        { name: "sections", type: "('titles' | 'axes' | 'legends' | 'headers' | 'data' | 'labels')[]", required: false, note: "The chart parts the walk reaches, in reading order. Defaults to every section." },
        { name: "maxFields", type: "number", required: false, note: "The most data fields read out for one mark. Defaults to 8." },
    ],
    'filter-controls': [
        { name: "fields", type: "(string | { field, widget?: 'auto' | 'checkboxes' | 'select' | 'range' | 'toggle', label?, all? })[]", required: false, note: "The fields that get a control. Listed fields always get one. When absent, the categorical, boolean, and temporal fields are chosen, up to four, skipping a field another interaction already filters: the color field under `legend-toggle`, a continuous axis field under `navigate` or `brush-zoom`." },
        { name: "mode", type: "'filter' | 'highlight'", required: false, note: "`filter` removes the rows that fail; `highlight` keeps them and mutes their marks. Defaults to `filter`." },
        { name: "placement", type: "'auto' | 'top' | 'bottom'", required: false, note: "Defaults to `auto`." },
        { name: "render", type: "boolean", required: false, note: "False draws nothing; the host draws its own controls and drives the preset through `dispatch`. Defaults to true." },
        { name: "initial", type: "Record<field, FilterValue>", required: false, note: "Filters applied when the chart mounts." },
        { name: "dimOpacity", type: "number", required: false, note: "Opacity of the marks that fail in `highlight` mode." },
    ],
    'context-menu': [
        { name: "items", type: "{ id, label }[]", required: true, note: "The actions the menu lists. Picking one emits a `menu-select` event whose `item` is the action's id and whose target is the selected marks." },
        { name: "gesture", type: "ContextMenuGesture", required: false, note: "How the reader picks the marks. Defaults to 'rectangle'. A rectangle or brush stays on screen to move or resize; a click or a long press picks one mark; a right-click opens the menu on a mark without highlighting it." },
        { name: "dimOpacity", type: "number", required: false, note: "" },
        { name: "reset", type: "ResetGesture[]", required: false, note: "Gestures that clear the selection and close the menu." },
        { name: "render", type: "boolean", required: false, note: "False draws nothing; the host draws its own menu from the selection events. Defaults to true." },
    ],
};
