// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// Generated by npm run gen:chart-types. Do not edit by hand.
import type { ChartAssemblyInput } from '../core/types';

/** Registered Vega-Lite template names. */
export type VegaLiteChartType =
    | "Area Chart"
    | "Bar Chart"
    | "Bar Table"
    | "Boxplot"
    | "Bullet Chart"
    | "Bump Chart"
    | "Calendar Heatmap"
    | "Candlestick Chart"
    | "Choropleth"
    | "Connected Scatter Plot"
    | "Density Plot"
    | "Donut Chart"
    | "ECDF Plot"
    | "Gantt Chart"
    | "Grouped Bar Chart"
    | "Heatmap"
    | "Histogram"
    | "KPI Card"
    | "Line Chart"
    | "Lollipop Chart"
    | "Map"
    | "Pie Chart"
    | "Pyramid Chart"
    | "Radar Chart"
    | "Range Area Chart"
    | "Ranged Dot Plot"
    | "Regression"
    | "Rose Chart"
    | "Scatter Plot"
    | "Slope Chart"
    | "Sparkline"
    | "Stacked Bar Chart"
    | "Streamgraph"
    | "Strip Plot"
    | "Violin Plot"
    | "Waterfall Chart";

/** Static property domains; runtime applicability still depends on data and encodings. */
export interface VegaLiteChartPropertiesMap {
    "Area Chart": {
        /** Column facet layout; availability is data dependent. */
        "facetColumns"?: number | undefined;
        "independentYAxis"?: boolean | undefined;
        "interpolate"?: "basis" | "cardinal" | "catmull-rom" | "linear" | "monotone" | "step" | "step-after" | "step-before" | undefined;
        "opacity"?: number | undefined;
        "stackMode"?: "center" | "layered" | "normalize" | undefined;
        "xAxisType"?: "nominal" | "temporal" | undefined;
        "yAxisType"?: "nominal" | "temporal" | undefined;
    };
    "Bar Chart": {
        "cornerRadius"?: number | undefined;
        /** Column facet layout; availability is data dependent. */
        "facetColumns"?: number | undefined;
        "independentYAxis"?: boolean | undefined;
        /** @deprecated Use showValueLabels. Legacy true requests labels; false means auto. */
        "showTextLabels"?: boolean | undefined;
        "showValueLabels"?: boolean | undefined;
        "sort"?: "value-asc" | "value-desc" | undefined;
        "xAxisType"?: "nominal" | "temporal" | undefined;
        "yAxisType"?: "nominal" | "temporal" | undefined;
    };
    "Bar Table": {
        /** Column facet layout; availability is data dependent. */
        "facetColumns"?: number | undefined;
        "independentYAxis"?: boolean | undefined;
        "maxRows"?: number | undefined;
        "showPercent"?: boolean | undefined;
    };
    "Boxplot": {
        "dodge"?: "auto" | "global" | "local" | undefined;
        /** Column facet layout; availability is data dependent. */
        "facetColumns"?: number | undefined;
        "includeZero_x"?: boolean | undefined;
        "includeZero_y"?: boolean | undefined;
        "independentYAxis"?: boolean | undefined;
        "logScale_x"?: boolean | undefined;
        "logScale_y"?: boolean | undefined;
        "showOutliers"?: boolean | undefined;
        "showPoints"?: boolean | undefined;
        "whiskerMethod"?: "iqr" | "minmax" | undefined;
    };
    "Bullet Chart": {
        /** Column facet layout; availability is data dependent. */
        "facetColumns"?: number | undefined;
        "independentYAxis"?: boolean | undefined;
    };
    "Bump Chart": {
        /** Column facet layout; availability is data dependent. */
        "facetColumns"?: number | undefined;
        "includeZero_x"?: boolean | undefined;
        "includeZero_y"?: boolean | undefined;
        "independentYAxis"?: boolean | undefined;
        "interpolate"?: "basis" | "cardinal" | "catmull-rom" | "linear" | "monotone" | "step" | "step-after" | "step-before" | undefined;
        "logScale_x"?: boolean | undefined;
        "logScale_y"?: boolean | undefined;
    };
    "Calendar Heatmap": {
        "colorScheme"?: "blues" | "github" | "greens" | "oranges" | "purples" | "reds" | "viridis" | undefined;
        "cornerRadius"?: number | undefined;
    };
    "Candlestick Chart": {
        /** Column facet layout; availability is data dependent. */
        "facetColumns"?: number | undefined;
        "includeZero_x"?: boolean | undefined;
        "includeZero_y"?: boolean | undefined;
        "independentYAxis"?: boolean | undefined;
        "logScale_x"?: boolean | undefined;
        "logScale_y"?: boolean | undefined;
    };
    "Choropleth": {
        "level"?: "auto" | "county" | "state" | undefined;
        "region"?: "auto" | "us" | "world" | undefined;
    };
    "Connected Scatter Plot": {
        /** Column facet layout; availability is data dependent. */
        "facetColumns"?: number | undefined;
        "includeZero_x"?: boolean | undefined;
        "includeZero_y"?: boolean | undefined;
        "independentYAxis"?: boolean | undefined;
        "logScale_x"?: boolean | undefined;
        "logScale_y"?: boolean | undefined;
    };
    "Density Plot": {
        "bandwidth"?: number | undefined;
        /** Column facet layout; availability is data dependent. */
        "facetColumns"?: number | undefined;
        "independentYAxis"?: boolean | undefined;
    };
    "Donut Chart": {
        /** Column facet layout; availability is data dependent. */
        "facetColumns"?: number | undefined;
        "independentYAxis"?: boolean | undefined;
        "innerRadius"?: number | undefined;
        /** @deprecated Use showValueLabels. Legacy true requests labels; false means auto. */
        "showTextLabels"?: boolean | undefined;
        "showValueLabels"?: boolean | undefined;
        "sortSlices"?: "ascending" | "descending" | "none" | undefined;
    };
    "ECDF Plot": {
        /** Column facet layout; availability is data dependent. */
        "facetColumns"?: number | undefined;
        "includeZero_x"?: boolean | undefined;
        "includeZero_y"?: boolean | undefined;
        "independentYAxis"?: boolean | undefined;
        "logScale_x"?: boolean | undefined;
        "logScale_y"?: boolean | undefined;
        "showPoints"?: boolean | undefined;
    };
    "Gantt Chart": {
        "cornerRadius"?: number | undefined;
        /** Column facet layout; availability is data dependent. */
        "facetColumns"?: number | undefined;
        "includeZero_x"?: boolean | undefined;
        "includeZero_y"?: boolean | undefined;
        "independentYAxis"?: boolean | undefined;
        "intervalLabels"?: boolean | undefined;
        "logScale_x"?: boolean | undefined;
        "logScale_y"?: boolean | undefined;
        "taskHeight"?: number | undefined;
    };
    "Grouped Bar Chart": {
        "dodge"?: "auto" | "global" | "local" | undefined;
        /** Column facet layout; availability is data dependent. */
        "facetColumns"?: number | undefined;
        "independentYAxis"?: boolean | undefined;
        /** @deprecated Use showValueLabels. Legacy true requests labels; false means auto. */
        "showTextLabels"?: boolean | undefined;
        "showValueLabels"?: boolean | undefined;
        "sort"?: "value-asc" | "value-desc" | undefined;
    };
    "Heatmap": {
        "colorScheme"?: "blueorange" | "blues" | "greens" | "greys" | "inferno" | "magma" | "oranges" | "plasma" | "purples" | "redblue" | "reds" | "turbo" | "viridis" | undefined;
        /** Column facet layout; availability is data dependent. */
        "facetColumns"?: number | undefined;
        "independentYAxis"?: boolean | undefined;
        /** @deprecated Use showValueLabels. Legacy true requests labels; false means auto. */
        "showTextLabels"?: boolean | undefined;
        "showValueLabels"?: boolean | undefined;
        "xAxisType"?: "nominal" | "temporal" | undefined;
        "yAxisType"?: "nominal" | "temporal" | undefined;
    };
    "Histogram": {
        "binCount"?: number | undefined;
        /** Column facet layout; availability is data dependent. */
        "facetColumns"?: number | undefined;
        "independentYAxis"?: boolean | undefined;
    };
    "KPI Card": {
        "behindThreshold"?: number | undefined;
        "includeZero_x"?: boolean | undefined;
        "includeZero_y"?: boolean | undefined;
        "layout"?: "grid" | "horizontal" | "vertical" | undefined;
        "logScale_x"?: boolean | undefined;
        "logScale_y"?: boolean | undefined;
        "style"?: boolean | undefined;
    };
    "Line Chart": {
        /** Column facet layout; availability is data dependent. */
        "facetColumns"?: number | undefined;
        "includeZero_x"?: boolean | undefined;
        "includeZero_y"?: boolean | undefined;
        "independentYAxis"?: boolean | undefined;
        "interpolate"?: "basis" | "cardinal" | "catmull-rom" | "linear" | "monotone" | "step" | "step-after" | "step-before" | undefined;
        "logScale_x"?: boolean | undefined;
        "logScale_y"?: boolean | undefined;
        "showPoints"?: boolean | undefined;
        "xAxisType"?: "nominal" | "temporal" | undefined;
        "yAxisType"?: "nominal" | "temporal" | undefined;
    };
    "Lollipop Chart": {
        "dotSize"?: number | undefined;
        /** Column facet layout; availability is data dependent. */
        "facetColumns"?: number | undefined;
        "independentYAxis"?: boolean | undefined;
        /** @deprecated Use showValueLabels. Legacy true requests labels; false means auto. */
        "showTextLabels"?: boolean | undefined;
        "showValueLabels"?: boolean | undefined;
        "sort"?: "value-asc" | "value-desc" | undefined;
        "xAxisType"?: "nominal" | "temporal" | undefined;
        "yAxisType"?: "nominal" | "temporal" | undefined;
    };
    "Map": {
        "includeZero_x"?: boolean | undefined;
        "includeZero_y"?: boolean | undefined;
        "logScale_x"?: boolean | undefined;
        "logScale_y"?: boolean | undefined;
        "projection"?: "azimuthalEquidistant" | "conicEqualArea" | "conicEquidistant" | "default" | "equalEarth" | "mercator" | "mollweide" | "orthographic" | "stereographic" | undefined;
        "projectionCenter"?: [-100, 45] | [-2, 54] | [-52, -14] | [-60, -15] | [-98, 39] | [0, 0] | [10, 50] | [10, 51] | [100, 60] | [105, 35] | [115, 5] | [128, 36] | [134, -25] | [138, 36] | [150, 0] | [2, 47] | [20, 0] | [45, 28] | [78, 22] | undefined;
        "region"?: "auto" | "us" | "world" | undefined;
    };
    "Pie Chart": {
        /** Column facet layout; availability is data dependent. */
        "facetColumns"?: number | undefined;
        "independentYAxis"?: boolean | undefined;
        "innerRadius"?: number | undefined;
        /** @deprecated Use showValueLabels. Legacy true requests labels; false means auto. */
        "showTextLabels"?: boolean | undefined;
        "showValueLabels"?: boolean | undefined;
        "sortSlices"?: "ascending" | "descending" | "none" | undefined;
    };
    "Pyramid Chart": {
        /** @deprecated Use showValueLabels. Legacy true requests labels; false means auto. */
        "showTextLabels"?: boolean | undefined;
        "showValueLabels"?: boolean | undefined;
    };
    "Radar Chart": {
        /** Column facet layout; availability is data dependent. */
        "facetColumns"?: number | undefined;
        "fillOpacity"?: number | undefined;
        "filled"?: boolean | undefined;
        "includeZero_x"?: boolean | undefined;
        "includeZero_y"?: boolean | undefined;
        "independentYAxis"?: boolean | undefined;
        "logScale_x"?: boolean | undefined;
        "logScale_y"?: boolean | undefined;
        "strokeWidth"?: number | undefined;
    };
    "Range Area Chart": {
        /** Column facet layout; availability is data dependent. */
        "facetColumns"?: number | undefined;
        "independentYAxis"?: boolean | undefined;
        "interpolate"?: "basis" | "linear" | "monotone" | "step" | "step-after" | "step-before" | undefined;
        "opacity"?: number | undefined;
    };
    "Ranged Dot Plot": {
        "includeZero_x"?: boolean | undefined;
        "includeZero_y"?: boolean | undefined;
        "logScale_x"?: boolean | undefined;
        "logScale_y"?: boolean | undefined;
    };
    "Regression": {
        /** Column facet layout; availability is data dependent. */
        "facetColumns"?: number | undefined;
        "includeZero_x"?: boolean | undefined;
        "includeZero_y"?: boolean | undefined;
        "independentYAxis"?: boolean | undefined;
        "logScale_x"?: boolean | undefined;
        "logScale_y"?: boolean | undefined;
        "polyOrder"?: number | undefined;
        "regressionMethod"?: "exp" | "linear" | "log" | "poly" | "pow" | "quad" | undefined;
    };
    "Rose Chart": {
        "alignment"?: "center" | "left" | undefined;
        /** Column facet layout; availability is data dependent. */
        "facetColumns"?: number | undefined;
        "independentYAxis"?: boolean | undefined;
        "padAngle"?: number | undefined;
        /** @deprecated Use showValueLabels. Legacy true requests labels; false means auto. */
        "showTextLabels"?: boolean | undefined;
        "showValueLabels"?: boolean | undefined;
        "sortSlices"?: "ascending" | "descending" | "none" | undefined;
    };
    "Scatter Plot": {
        /** Column facet layout; availability is data dependent. */
        "facetColumns"?: number | undefined;
        "includeZero_x"?: boolean | undefined;
        "includeZero_y"?: boolean | undefined;
        "independentYAxis"?: boolean | undefined;
        "logScale_x"?: boolean | undefined;
        "logScale_y"?: boolean | undefined;
        "opacity"?: number | undefined;
    };
    "Slope Chart": {
        /** Column facet layout; availability is data dependent. */
        "facetColumns"?: number | undefined;
        "includeZero_x"?: boolean | undefined;
        "includeZero_y"?: boolean | undefined;
        "independentYAxis"?: boolean | undefined;
        "logScale_x"?: boolean | undefined;
        "logScale_y"?: boolean | undefined;
        "showSeriesInLabel"?: boolean | undefined;
        "showText"?: boolean | undefined;
    };
    "Sparkline": {
        "baseline"?: "mean" | "median" | "none" | "zero" | undefined;
        /** Column facet layout; availability is data dependent. */
        "facetColumns"?: number | undefined;
        "includeZero_x"?: boolean | undefined;
        "includeZero_y"?: boolean | undefined;
        "interpolate"?: "basis" | "cardinal" | "catmull-rom" | "linear" | "monotone" | "step" | "step-after" | "step-before" | undefined;
        "logScale_x"?: boolean | undefined;
        "logScale_y"?: boolean | undefined;
        "trendWidth"?: number | undefined;
    };
    "Stacked Bar Chart": {
        /** Column facet layout; availability is data dependent. */
        "facetColumns"?: number | undefined;
        "independentYAxis"?: boolean | undefined;
        /** @deprecated Use showValueLabels. Legacy true requests labels; false means auto. */
        "showTextLabels"?: boolean | undefined;
        "showValueLabels"?: boolean | undefined;
        "sort"?: "value-asc" | "value-desc" | undefined;
        "stackMode"?: "center" | "normalize" | undefined;
    };
    "Streamgraph": {
        /** Column facet layout; availability is data dependent. */
        "facetColumns"?: number | undefined;
        "independentYAxis"?: boolean | undefined;
        "interpolate"?: "basis" | "cardinal" | "catmull-rom" | "linear" | "monotone" | "step" | "step-after" | "step-before" | undefined;
    };
    "Strip Plot": {
        /** Column facet layout; availability is data dependent. */
        "facetColumns"?: number | undefined;
        "includeZero_x"?: boolean | undefined;
        "includeZero_y"?: boolean | undefined;
        "independentYAxis"?: boolean | undefined;
        "logScale_x"?: boolean | undefined;
        "logScale_y"?: boolean | undefined;
        "opacity"?: number | undefined;
        "pointSize"?: number | undefined;
        "stepWidth"?: number | undefined;
    };
    "Violin Plot": {
        "bandwidth"?: number | undefined;
        "independentYAxis"?: boolean | undefined;
        "medianWidth"?: number | undefined;
        "showContour"?: boolean | undefined;
        "showMedian"?: boolean | undefined;
        "showPoints"?: boolean | undefined;
    };
    "Waterfall Chart": {
        "cornerRadius"?: number | undefined;
        /** Column facet layout; availability is data dependent. */
        "facetColumns"?: number | undefined;
        "independentYAxis"?: boolean | undefined;
        /** @deprecated Use showValueLabels. Legacy true requests labels; false means auto. */
        "showTextLabels"?: boolean | undefined;
        "showValueLabels"?: boolean | undefined;
        "totals"?: "auto" | "both" | "first" | "last" | "none" | undefined;
    };
}

/** Opt-in authoring union. All other native chart_spec fields are preserved. */
export type VegaLiteChartSpec = {
    [C in VegaLiteChartType]:
        Omit<ChartAssemblyInput['chart_spec'], 'chartType' | 'chartProperties'> & {
            chartType: C;
            chartProperties?: VegaLiteChartPropertiesMap[C];
        };
}[VegaLiteChartType];
